Update README.md
sanity-io/next-sanity pull request #589
Opened 2023-08-29 07:26 UTC by JanKups

App-router example fixes: Added next/headers, renamed client

2023-08-30 17:53 UTC, mariuslundgard commented on README.md
> +import { draftMode } from "next/headers";
Please follow the prettier rules for formatting:

```suggestion
import {draftMode} from 'next/headers'
```

2023-09-03 19:38 UTC, stipsan requested changes

2023-09-03 19:38 UTC, stipsan commented on README.md
> +const sanityClient = createClient({
```suggestion
const client = createClient({
```

This should continue to be `client` as that's what we use in our starter templates and most of our educational material 😄

2023-09-13 10:47 UTC, stipsan approved these changes

2023-09-13 10:50 UTC, merged